import { addCollection, Icon as IconifyIcon } from "@iconify/react/offline";
import type { IconifyJSON } from "@iconify/types";
import collection from "../iconify-mdi.json";

/** Bundled MDI subset (offline). To add an icon, copy it from `@iconify-json/mdi` into `iconify-mdi.json`. */
addCollection(collection as IconifyJSON);

const ICONS = {
  play: "mdi:play",
  playCircle: "mdi:play-circle-outline",
  stop: "mdi:stop",
  dice: "mdi:dice-5",
  save: "mdi:content-save-outline",
  refresh: "mdi:refresh",
  usb: "mdi:usb",
  connect: "mdi:link-variant",
  disconnect: "mdi:link-variant-off",
  midiHelp: "mdi:midi-port",
  midi: "mdi:midi",
  piano: "mdi:piano",
  controls: "mdi:gamepad-variant-outline",
  expansion: "mdi:puzzle-outline",
  board: "mdi:view-dashboard-outline",
  library: "mdi:bookshelf",
  system: "mdi:cog-outline",
  external: "mdi:open-in-new",
  tune: "mdi:tune-variant",
  mfx: "mdi:waveform",
  strings: "mdi:guitar-acoustic",
  others: "mdi:dots-horizontal",
  master: "mdi:volume-high",
  chorus: "mdi:waves",
  reverb: "mdi:blur",
  close: "mdi:close",
  eraser: "mdi:eraser",
  back: "mdi:arrow-left",
  search: "mdi:magnify",
  notesOff: "mdi:music-off",
  blocks: "mdi:view-grid-outline",
  chain: "mdi:vector-polyline",
  copy: "mdi:content-copy",
  paste: "mdi:content-paste",
  scene: "mdi:playlist-music",
  tempo: "mdi:metronome",
  help: "mdi:help-circle-outline",
  alert: "mdi:alert-outline",
  keyboard: "mdi:keyboard",
  live: "mdi:circle",
  dirty: "mdi:circle-medium",
  guitar: "mdi:guitar-electric",
  info: "mdi:information-outline",
  loop: "mdi:repeat",
  oneShot: "mdi:repeat-once",
  merge: "mdi:source-merge",
  dry: "mdi:sine-wave",
  fadeIn: "mdi:trending-up",
  fadeOut: "mdi:trending-down",
  loopEnd: "mdi:arrow-collapse-right",
  overdub: "mdi:layers-plus",
  replace1: "mdi:file-replace-outline",
  replace2: "mdi:file-replace",
  playMulti: "mdi:play-box-multiple-outline",
  playSingle: "mdi:play-box-outline",
  xfade: "mdi:swap-horizontal",
  fastForward: "mdi:fast-forward",
  rewind: "mdi:rewind",
  skipNext: "mdi:skip-next",
  skipPrevious: "mdi:skip-previous",
  shuffle: "mdi:shuffle-variant",
  recordPlayer: "mdi:record-player",
  speedSlow: "mdi:speedometer-slow",
  speedNormal: "mdi:speedometer-medium",
  speedFast: "mdi:speedometer",
  record: "mdi:record-circle",
  folderOpen: "mdi:folder-open-outline",
  eject: "mdi:eject",
  keyRemove: "mdi:key-remove",
  key: "mdi:key-variant",
  emailSend: "mdi:email-send-outline",
  archive: "mdi:folder-zip-outline",
  restore: "mdi:restore",
  note: "mdi:music-note",
  mic: "mdi:microphone-outline",
  radio: "mdi:radio",
  equalizer: "mdi:equalizer",
  chevronDown: "mdi:chevron-down",
  autoFix: "mdi:auto-fix",
  arrowUp: "mdi:arrow-up",
  arrowDown: "mdi:arrow-down",
  chevronRight: "mdi:chevron-right",
  chevronLeft: "mdi:chevron-left",
  measureAuto: "mdi:alpha-a-circle-outline",
  measureFree: "mdi:infinity",
  download: "mdi:download",
  upload: "mdi:upload",
  deleteOutline: "mdi:delete-outline",
  importAudio: "mdi:tray-arrow-up",
  exportAudio: "mdi:tray-arrow-down",
  trash: "mdi:trash-can-outline",
  fileMusic: "mdi:file-music-outline",
  pause: "mdi:pause",
  fullscreen: "mdi:fullscreen",
  fullscreenExit: "mdi:fullscreen-exit",
  heart: "mdi:heart",
  edit: "mdi:pencil-outline",
  view: "mdi:eye-outline",
  syncImmediate: "mdi:lightning-bolt",
  syncMeasure: "mdi:ruler",
  variationA: "mdi:alpha-a-box-outline",
  variationB: "mdi:alpha-b-box-outline",
  variationC: "mdi:alpha-c-box-outline",
  variationD: "mdi:alpha-d-box-outline",
  intro: "mdi:ray-start-arrow",
  ending: "mdi:flag-checkered",
  fill: "mdi:music-note-plus",
  introRec: "mdi:record-rec",
  recEnd: "mdi:stop-circle-outline",
  phantom: "mdi:flash",
  phantomOff: "mdi:flash-off-outline",
  compressor: "mdi:arrow-collapse-vertical",
  noiseGate: "mdi:gate",
  headphones: "mdi:headphones",
  volumeOff: "mdi:volume-off",
  speaker: "mdi:speaker",
  power: "mdi:power",
  toggle: "mdi:toggle-switch-outline",
  moment: "mdi:gesture-tap-hold",
  undo: "mdi:undo",
  redo: "mdi:redo",
  plus: "mdi:plus",
  moveLeft: "mdi:arrow-left-bold-outline",
  moveRight: "mdi:arrow-right-bold-outline",
  grid: "mdi:table-large",
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  size = "1em",
}: {
  name: IconName;
  className?: string;
  size?: number | string;
}) {
  return (
    <IconifyIcon
      icon={ICONS[name]}
      width={size}
      height={size}
      className={className ? `ui-icon ${className}` : "ui-icon"}
      aria-hidden="true"
      focusable="false"
    />
  );
}
